### PR TITLE
Added Azure queries

### PR DESCRIPTION
**Pull request by ville87**
Added custom Azure queries and categorized them.
Queries are originally from: https://hausec.com/2020/11/23/azurehound-cypher-cheatsheet/

### CODE REVIEW

**Comment by sploutchy** [comment]
Hi @ville87 ,
Thanks for the PR!
One more question :) could you update the README?
If you don't have time, I'll do it when I do!
Cheers

**Comment by ville87** [comment]
Hi @sploutchy, done: https://github.com/CompassSecurity/BloodHoundQueries/pull/12/files
:-)

**Comment by sploutchy** [comment]
Adding azure queries.

**Comment by sploutchy** [comment]
Thx

**Pull request merged**
